# Generated by Django 5.0.6 on 2024-06-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_ticket_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_choices',
            new_name='ticket_status',
        ),
    ]
